import { Mutation } from "@/app/_mutation/model";

export const mutationDummy: Mutation[] = [
  {
    id: "1",
    date: "2025-01-02",
    type: "income",
    amount: 2000000,
    category: "Operasional",
    information: "SPP Santri",
    description: "Pembayaran SPP santri kelas 7–9",
  },
  {
    id: "2",
    date: "2025-01-04",
    type: "outcome",
    amount: 450000,
    category: "Operasional",
    information: "Toko ATK Amanah",
    description: "Pulpen, buku tulis, spidol",
  },
  {
    id: "3",
    date: "2025-01-06",
    type: "income",
    amount: 5000000,
    category: "Operasional",
    information: "Donasi wali santri",
    description: "Donasi pembangunan asrama",
  },
  {
    id: "4",
    date: "2025-01-08",
    type: "outcome",
    amount: 1250000,
    category: "Konsumsi",
    information: "Warung Sembako Barokah",
    description: "Beras, minyak, telur, bumbu",
  },
  {
    id: "5",
    date: "2025-01-10",
    type: "outcome",
    amount: 800000,
    category: "Pemeliharaan",
    information: "Tukang Bangunan",
    description: "Perbaikan atap ruang kelas",
  },
  {
    id: "6",
    date: "2025-01-12",
    type: "income",
    category: "Operasional",
    amount: 950000,
    information: "Infak Jumat",
    description: "Infak jamaah sholat Jumat",
  },
];
